---
- name: install java11
  hosts: all
  become: yes
  tasks:
    - name: install java11
      ansible.builtin.package:
        name: "{{ java_package_name }}"
        update_cache: yes
        state: present
