---
- name: install java17
  hosts: all
  become: yes
  tasks:
    - name: install java17
      ansible.builtin.package:
        name: openjdk-17-jdk
        update_cache: yes
        state: present




        