---
- name: Installing wildfly in ubuntu
  hosts: all
  become: yes
  vars:
    tar_package_url: https://github.com/wildfly/wildfly/releases/download/26.1.2.Final/wildfly-26.1.2.Final.tar.gz
    wildfly_config_path: /opt/wildfly/docs/contrib/scripts/systemd/
    wildfly_home: /opt/wildfly 
    config_folder: /etc/wildfly
    group_name: wildfly
  tasks:
    - name: install java-11-openjdk-devel  
      ansible.builtin.yum:
        name: java-11-openjdk-devel   
        update_cache: yes
        state: present
    - name: untar file
      ansible.builtin.unarchive:
        src: "{{ tar_package_url }}"
        dest: /tmp/
        remote_src: yes
    - name: creating directory /opt/wildfly
      ansible.builtin.file:
        path: "{{ wildfly_home }}"
        state: directory
        mode: '0755'    
    - name: copy in ansible
      ansible.builtin.copy:
        src: /tmp/wildfly-26.1.2.Final/
        dest: "{{ wildfly_home }}"
        remote_src: yes
    - name: remove the wildfly-26.1.2.Final from /tmp
      ansible.builtin.file :
        path: /tmp/wildfly-26.1.2.Final.
        state: absent
    - name: groupadd in ansible
      ansible.builtin.group:
        name: "{{ group_name }}"
        system: true
    - name: useradd in ansible
      ansible.builtin.user:
        name: wildfly
        shell: /sbin/nologin 
        system: true
        home: /opt/wildfly
        group: "{{ group_name }}"
    - name: create configuration directory
      ansible.builtin.file:
        path: "{{ config_folder }}"
        state: directory
        mode: '0755'
    - name: copy in configuration necessary
      ansible.builtin.copy:
        src: "{{ wildfly_config_path }}wildfly.conf"
        dest: "{{ config_folder }}"
        remote_src: yes
    - name: copy in configuration necessary
      ansible.builtin.copy:
        src: "{{ wildfly_config_path }}wildfly.service"
        dest: /etc/systemd/system/
        remote_src: yes
    - name: copy in configuration necessary
      ansible.builtin.copy:
        src: "{{ wildfly_config_path }}launch.sh"
        dest: /opt/wildfly/bin/
        remote_src: yes        
    - name: changing file permissions
      ansible.builtin.command: chmod +x /opt/wildfly/bin/launch.sh
    - name: changing owner permissions
      ansible.builtin.command: chown -R wildfly:wildfly "{{ wildfly_home }}"
    - name: Reload systemd service
      ansible.builtin.command: systemctl daemon-reload
    - name: Start and enable WildFly service
      ansible.builtin.systemd:
        name: wildfly
        enabled: yes
        state: started
          

      
                     
           
           
              