---
- name: install dotnet on ubuntu
  hosts: all
  become: yes
  vars:
    dotnet_url: https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb 
    sdk_name: dotnet-sdk-7.0 
    transport_name: apt-transport-https
    dotnet_name: dotnet-runtime-7.0  
  tasks:
    - name: install microsoft package
      ansible.builtin.get_url:
        url: "{{ dotnet_url }}" 
        dest: /tmp
        mode: 0440
    - name: install microsoft debian package
      ansible.builtin.apt:
        deb: /tmp/packages-microsoft-prod.deb 
    - name: Install dotnetcore SDK
      ansible.builtin.apt:
        name: 
          - "{{ transport_name }}"
          - "{{ sdk_name }}"
        state: present
        update_cache: yes
    - name: Install dotnetcore runtime
      ansible.builtin.apt:
        name: 
          - "{{ transport_name }}"
          - "{{ dotnet_name }}" 
        state: present
        update_cache: yes 

dotnet new console -o HelloWorld
cd  HelloWorld
dotnet run   

     
      
        
