---
- name: installind haproxy on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: install software-properties-common
      ansible.builtin.apt:
        name: software-properties-common  
        update_cache: yes
        state: present
    - name: Add repository
      ansible.builtin.apt_repository:
        repo: ppa:vbernat/haproxy-2.6
        state: present 
    - name: install ha-proxy
      ansible.builtin.apt:
        name: haproxy  
        update_cache: yes
        state: present
    - name: check status 
      ansible.builtin.command: systemctl status haproxy
    - name: copy file
      ansible.builtin.copy:
        src: /etc/haproxy/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg-org
        remote_src: yes 
    - name: copy file
      ansible.builtin.copy:
        src: ./haproxy.config
        dest: /etc/haproxy/haproxy.cfg
        remote_src: no 
    - name: restart 
      ansible.builtin.command: systemctl restart haproxy
                